spring.application.name=EmployeeManagementSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management_system
spring.datasource.username=postgres
spring.datasource.password=#Hello3006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=Mallika
spring.security.user.password=#Hello3006